Started boilerplate for ExternalMessage-API. Breaks unit tests because some permission is missing:
de.symeda.sormas.api.utils.ValidationRuntimeException: The following user right(s) are required based on other user right(s): <br> <b>[Edit surveys]</b> required by 'EXTERNAL_MESSAGE_SURVEY_RESPONSE_PROCESS'<br><b>[View surveys]</b> required by 'EXTERNAL_MESSAGE_SURVEY_RESPONSE_PROCESS'<br><b>[Create surveys]</b> required by 'EXTERNAL_MESSAGE_SURVEY_RESPONSE_PROCESS'<br><b>[Delete surveys]</b> required by 'EXTERNAL_MESSAGE_SURVEY_RESPONSE_PROCESS'<br><b>[View survey tokens]</b> required by 'EXTERNAL_MESSAGE_SURVEY_RESPONSE_PROCESS'<br>