#5823: Fix query: Select distinct contacts
- Added Contact.changeDate to avoid query failure:
JdbcSQLSyntaxErrorException: Order by expression "contact0_.changedate"
must be in the result list in this case